# Generated by Codex on 2026-05-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("subtitulo", models.CharField(max_length=200)),
                ("cuerpo", ckeditor.fields.RichTextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("imagen", models.ImageField(blank=True, null=True, upload_to="pages/")),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paginas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Página",
                "verbose_name_plural": "Páginas",
                "ordering": ["-fecha"],
            },
        ),
    ]

